// Central place that maps a string icon name (used in the data files) to an
// actual lucide-react component. Keeps data files free of JSX/imports so
// non-developers can edit portfolioData.js without touching React code.
import {
  Cloud,
  GitBranch,
  Container,
  FileCode2,
  Settings2,
  ShieldCheck,
  Activity,
  Terminal,
  Code2,
  Boxes,
  KeyRound,
  FileX2,
  Lock,
  ScanSearch,
  Box,
  UserCog,
  Network,
  GitPullRequestArrow,
  Github,
  Linkedin,
  Mail,
  ExternalLink,
  Menu,
  X,
  ArrowUpRight,
  Send,
} from 'lucide-react';

export const iconMap = {
  Cloud,
  GitBranch,
  Container,
  FileCode2,
  Settings2,
  ShieldCheck,
  Activity,
  Terminal,
  Code2,
  Boxes,
  KeyRound,
  FileX2,
  Lock,
  ScanSearch,
  Box,
  UserCog,
  Network,
  GitPullRequestArrow,
  Github,
  Linkedin,
  Mail,
  ExternalLink,
  Menu,
  X,
  ArrowUpRight,
  Send,
};
